import type { PRItem, IssueItem, CIItem, ActivityItem, ReleaseItem, DeploymentItem } from "@/types";

const h = (n: number) => new Date(Date.now() - n * 3_600_000).toISOString();
const d = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString();
const m = (n: number) => new Date(Date.now() - n * 60_000).toISOString();

export const MOCK_PRS: PRItem[] = [
  {
    type: "pr",
    id: 1,
    title: "feat: add streaming support to inference pipeline",
    repo: "acme/ml-core",
    author: "sarahk",
    assignee: null,
    number: 847,
    reviews: { approved: 2, requested: 1 },
    comments: 14,
    draft: false,
    state: "open",
    age: h(2),
    labels: [
      { name: "enhancement", color: "0075ca" },
      { name: "perf", color: "6ee7b7" },
    ],
    url: "https://github.com/acme/ml-core/pull/847",
  },
  {
    type: "pr",
    id: 2,
    title: "fix: race condition in job queue processor",
    repo: "acme/worker",
    author: "themarcus",
    assignee: null,
    number: 231,
    reviews: { approved: 0, requested: 2 },
    comments: 6,
    draft: false,
    state: "open",
    age: h(5),
    labels: [
      { name: "bug", color: "d73a4a" },
      { name: "urgent", color: "fca5a5" },
    ],
    url: "https://github.com/acme/worker/pull/231",
  },
  {
    type: "pr",
    id: 3,
    title: "refactor: migrate from REST to tRPC",
    repo: "acme/api",
    author: "jliu",
    assignee: null,
    number: 419,
    reviews: { approved: 1, requested: 0 },
    comments: 23,
    draft: true,
    state: "open",
    age: d(1),
    labels: [{ name: "refactor", color: "a78bfa" }],
    url: "https://github.com/acme/api/pull/419",
  },
  {
    type: "pr",
    id: 4,
    title: "chore: bump all dependencies to latest",
    repo: "acme/frontend",
    author: "bot[renovate]",
    assignee: null,
    number: 1102,
    reviews: { approved: 0, requested: 0 },
    comments: 0,
    draft: false,
    state: "open",
    age: h(3),
    labels: [{ name: "dependencies", color: "9ca3af" }],
    url: "https://github.com/acme/frontend/pull/1102",
  },
  {
    type: "pr",
    id: 5,
    title: "docs: update contributing guide with new branch conventions",
    repo: "acme/ml-core",
    author: "priya_d",
    assignee: null,
    number: 848,
    reviews: { approved: 3, requested: 0 },
    comments: 2,
    draft: false,
    state: "open",
    age: h(6),
    labels: [{ name: "documentation", color: "86efac" }],
    url: "https://github.com/acme/ml-core/pull/848",
  },
];

export const MOCK_ISSUES: IssueItem[] = [
  {
    type: "issue",
    id: 1,
    title: "Memory leak in long-running inference jobs",
    repo: "acme/ml-core",
    number: 901,
    labels: [
      { name: "bug", color: "d73a4a" },
      { name: "critical", color: "fca5a5" },
    ],
    assignee: "sarahk",
    comments: 8,
    age: d(1),
    state: "open",
    url: "https://github.com/acme/ml-core/issues/901",
  },
  {
    type: "issue",
    id: 2,
    title: "Support batching for embedding requests",
    repo: "acme/api",
    number: 503,
    labels: [{ name: "enhancement", color: "0075ca" }],
    assignee: null,
    comments: 3,
    age: d(3),
    state: "open",
    url: "https://github.com/acme/api/issues/503",
  },
  {
    type: "issue",
    id: 3,
    title: "CLI --watch flag breaks on Windows paths",
    repo: "acme/cli",
    number: 78,
    labels: [
      { name: "bug", color: "d73a4a" },
      { name: "platform", color: "a5b4fc" },
    ],
    assignee: "themarcus",
    comments: 11,
    age: h(12),
    state: "open",
    url: "https://github.com/acme/cli/issues/78",
  },
  {
    type: "issue",
    id: 4,
    title: "Add Prometheus metrics endpoint",
    repo: "acme/worker",
    number: 245,
    labels: [
      { name: "enhancement", color: "0075ca" },
      { name: "observability", color: "f59e0b" },
    ],
    assignee: null,
    comments: 4,
    age: d(5),
    state: "open",
    url: "https://github.com/acme/worker/issues/245",
  },
  {
    type: "issue",
    id: 5,
    title: "Rate limiter doesn't respect burst parameter",
    repo: "acme/api",
    number: 501,
    labels: [{ name: "bug", color: "d73a4a" }],
    assignee: "jliu",
    comments: 7,
    age: d(2),
    state: "open",
    url: "https://github.com/acme/api/issues/501",
  },
];

export const MOCK_CI: CIItem[] = [
  {
    type: "ci",
    id: 1,
    name: "CI / test (ubuntu, node 20)",
    repo: "acme/ml-core",
    branch: "feat/streaming",
    status: "success",
    duration: "4m 12s",
    age: h(2),
    triggered: "push",
    url: "https://github.com/acme/ml-core/actions/runs/1001",
  },
  {
    type: "ci",
    id: 2,
    name: "CI / test (ubuntu, node 18)",
    repo: "acme/api",
    branch: "main",
    status: "failure",
    duration: "1m 58s",
    age: h(3),
    triggered: "push",
    url: "https://github.com/acme/api/actions/runs/1002",
  },
  {
    type: "ci",
    id: 3,
    name: "Deploy / staging",
    repo: "acme/frontend",
    branch: "main",
    status: "running",
    duration: "—",
    age: m(12),
    triggered: "push",
    url: "https://github.com/acme/frontend/actions/runs/1003",
  },
  {
    type: "ci",
    id: 4,
    name: "CI / lint",
    repo: "acme/worker",
    branch: "fix/race-condition",
    status: "success",
    duration: "48s",
    age: h(5),
    triggered: "pull_request",
    url: "https://github.com/acme/worker/actions/runs/1004",
  },
  {
    type: "ci",
    id: 5,
    name: "Deploy / production",
    repo: "acme/api",
    branch: "v2.4.1",
    status: "success",
    duration: "8m 03s",
    age: d(1),
    triggered: "release",
    url: "https://github.com/acme/api/actions/runs/1005",
  },
  {
    type: "ci",
    id: 6,
    name: "CI / type-check",
    repo: "acme/frontend",
    branch: "refactor/trpc",
    status: "failure",
    duration: "2m 11s",
    age: d(1),
    triggered: "pull_request",
    url: "https://github.com/acme/frontend/actions/runs/1006",
  },
];

export const MOCK_RELEASES: ReleaseItem[] = [
  {
    type: "release",
    id: 1,
    repo: "acme/api",
    tag: "v2.4.1",
    name: "v2.4.1 — Hotfix: rate limiter",
    prerelease: false,
    age: d(1),
    url: "https://github.com/acme/api/releases/tag/v2.4.1",
  },
  {
    type: "release",
    id: 2,
    repo: "acme/ml-core",
    tag: "v1.9.0",
    name: "v1.9.0 — Streaming support",
    prerelease: false,
    age: d(3),
    url: "https://github.com/acme/ml-core/releases/tag/v1.9.0",
  },
  {
    type: "release",
    id: 3,
    repo: "acme/frontend",
    tag: "v3.0.0-rc.1",
    name: "v3.0.0 Release Candidate 1",
    prerelease: true,
    age: h(5),
    url: "https://github.com/acme/frontend/releases/tag/v3.0.0-rc.1",
  },
  {
    type: "release",
    id: 4,
    repo: "acme/cli",
    tag: "v0.12.0",
    name: "v0.12.0 — Windows path fixes",
    prerelease: false,
    age: d(7),
    url: "https://github.com/acme/cli/releases/tag/v0.12.0",
  },
];

export const MOCK_DEPLOYMENTS: DeploymentItem[] = [
  {
    type: "deployment",
    id: 1,
    repo: "acme/api",
    environment: "production",
    status: "success",
    ref: "v2.4.1",
    creator: "priya_d",
    age: d(1),
    url: "https://github.com/acme/api/deployments",
  },
  {
    type: "deployment",
    id: 2,
    repo: "acme/frontend",
    environment: "staging",
    status: "in_progress",
    ref: "main",
    creator: "jliu",
    age: m(12),
    url: "https://github.com/acme/frontend/deployments",
  },
  {
    type: "deployment",
    id: 3,
    repo: "acme/worker",
    environment: "production",
    status: "failure",
    ref: "v1.3.2",
    creator: "themarcus",
    age: h(6),
    url: "https://github.com/acme/worker/deployments",
  },
  {
    type: "deployment",
    id: 4,
    repo: "acme/ml-core",
    environment: "staging",
    status: "pending",
    ref: "feat/streaming",
    creator: "sarahk",
    age: h(2),
    url: "https://github.com/acme/ml-core/deployments",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    type: "activity",
    id: 1,
    kind: "commit",
    text: "Pushed 3 commits to feat/streaming",
    repo: "acme/ml-core",
    age: h(2),
    ref: "a3f9c12",
    url: "https://github.com/acme/ml-core/commit/a3f9c12",
  },
  {
    type: "activity",
    id: 2,
    kind: "comment",
    text: "Commented on Issue #901",
    repo: "acme/ml-core",
    age: h(3),
    ref: "Issue #901",
    url: "https://github.com/acme/ml-core/issues/901",
  },
  {
    type: "activity",
    id: 3,
    kind: "pr_opened",
    text: "Opened PR #848",
    repo: "acme/ml-core",
    age: h(6),
    ref: "PR #848",
    url: "https://github.com/acme/ml-core/pull/848",
  },
  {
    type: "activity",
    id: 4,
    kind: "review",
    text: "Reviewed PR #231 — requested changes",
    repo: "acme/worker",
    age: h(5),
    ref: "PR #231",
    url: "https://github.com/acme/worker/pull/231",
  },
  {
    type: "activity",
    id: 5,
    kind: "commit",
    text: "Pushed 1 commit to main",
    repo: "acme/api",
    age: d(1),
    ref: "7bd2e41",
    url: "https://github.com/acme/api/commit/7bd2e41",
  },
  {
    type: "activity",
    id: 6,
    kind: "issue_closed",
    text: "Closed Issue #497",
    repo: "acme/api",
    age: d(1),
    ref: "Issue #497",
    url: "https://github.com/acme/api/issues/497",
  },
];
